.github/workflows/release.yml
laktory/_version.py

version-bump-0.0.22

---

CHANGELOG.md
laktory/_version.py

version-bump-0.1.1

---

CHANGELOG.md
laktory/_version.py

version-bump-0.1.2

---

CHANGELOG.md
laktory/_version.py

version-bump-0.1.3

---

CHANGELOG.md
laktory/_version.py

version-bump-0.1.4

---

CHANGELOG.md
laktory/_version.py

version-bump-0.1.5

---

CHANGELOG.md
laktory/_version.py

version-bump-0.1.6

---

CHANGELOG.md
laktory/_version.py

version-bump-0.1.7

---

CHANGELOG.md
laktory/_version.py

version-bump-0.1.8

---

CHANGELOG.md
laktory/_version.py

version-bump-0.1.9

---

CHANGELOG.md
laktory/_version.py

version-bump-0.1.10

---

CHANGELOG.md
laktory/_version.py

version-bump-0.2.1

---

CHANGELOG.md
laktory/_version.py

version-bump-0.2.2

---

CHANGELOG.md
laktory/_version.py

version-bump-0.3.1

---

CHANGELOG.md
laktory/_version.py

version-bump-0.3.2

---

CHANGELOG.md
laktory/_version.py

version-bump-0.3.3

---

CHANGELOG.md
laktory/_version.py

version-bump-0.3.4

---

CHANGELOG.md
laktory/_version.py

version-bump-0.4.1

---

CHANGELOG.md
laktory/_version.py

version-bump-0.4.2

---

CHANGELOG.md
laktory/_version.py

version-bump-0.4.3

---

CHANGELOG.md
laktory/_version.py

version-bump-0.4.4

---

CHANGELOG.md
laktory/_version.py

version-bump-0.4.5

---

CHANGELOG.md
laktory/_version.py

version-bump-0.4.6

---

CHANGELOG.md
laktory/_version.py

version-bump-0.4.7

---

CHANGELOG.md
laktory/_version.py

version-bump-0.4.8

---

CHANGELOG.md
laktory/_version.py

version-bump-0.4.9

---

CHANGELOG.md
laktory/_version.py

version-bump-0.4.10

---

CHANGELOG.md
docs/concepts/variables.md
laktory/_settings.py
laktory/constants.py
laktory/models/resources/databricks/dbfsfile.py
laktory/models/resources/databricks/notebook.py
laktory/models/resources/databricks/workspacefile.py
laktory/resources/quickstart-stacks/workflows/resources/notebooks.yaml
tests/test_notebook.py
tests/test_stack.py
tests/test_workspacefile.py

Update for https://github.com/okube-ai/laktory/issues/263

Refactored default paths for Workspace, DBFS and Notebooks files.

---

laktory/models/resources/databricks/job.py

Fixed issue https://github.com/okube-ai/laktory/issues/275

Added support for source type in Job SQL Task model.

---

CHANGELOG.md
laktory/models/resources/databricks/job.py

Solved https://github.com/okube-ai/laktory/issues/274

Set query as optional in Databricks job sql task

---

CHANGELOG.md
laktory/_version.py

version-bump-0.5.1

---

CHANGELOG.md
laktory/_version.py

version-bump-0.5.2

---

CHANGELOG.md
laktory/_version.py

version-bump-0.5.3

---

CHANGELOG.md
laktory/_version.py

version-bump-0.5.4

---

CHANGELOG.md
laktory/_version.py

version-bump-0.5.5

---

CHANGELOG.md
laktory/_version.py

version-bump-0.5.7

---

CHANGELOG.md
laktory/_version.py

version-bump-0.5.8

---

CHANGELOG.md
laktory/_version.py

version-bump-0.5.9

---

CHANGELOG.md
laktory/_version.py

version-bump-0.5.10

---

CHANGELOG.md
laktory/_version.py

version-bump-0.6.1

---

CHANGELOG.md
laktory/_version.py

version-bump-0.6.2

---

CHANGELOG.md
laktory/_version.py

version-bump-0.6.4

---

CHANGELOG.md
laktory/models/datasinks/basedatasink.py
tests/test_datasinks_merge.py

Fixed issue https://github.com/okube-ai/laktory/issues/361.

Fixed issue with SCD Type 2 merge without delete condition

---

CHANGELOG.md
laktory/models/stacks/terraformstack.py

Fixed lookup_existing for resources that require options to be passed down to IaC tool

---

CHANGELOG.md
laktory/_version.py

version-bump-0.6.7

---

CHANGELOG.md
laktory/_version.py

version-bump-0.6.8

---

CHANGELOG.md
laktory/_version.py

version-bump-0.6.9

---

CHANGELOG.md
laktory/models/resources/databricks/__init__.py
laktory/models/resources/databricks/workspacebinding.py
laktory/models/stacks/stack.py
tests/test_stack.py
tests/test_workspacebinding.py

Adding the ability to bind workspace to different securable objects (catalog, schemas, credentials etc.).

Add workspace binding resource

---

CHANGELOG.md
laktory/_version.py

version-bump-0.6.10

---

CHANGELOG.md
laktory/_version.py

version-bump-0.7.1

---

CHANGELOG.md
laktory/_version.py

version-bump-0.7.2

---

CHANGELOG.md
laktory/models/resources/databricks/permissions.py
tests/test_stack.py

Added support for authorizations in Databricks Permissions.

Databricks Permission authorizations

---

CHANGELOG.md
laktory/_version.py

version-bump-0.7.3

---

CHANGELOG.md
laktory/_version.py

version-bump-0.7.4

---

README.md

Preliminary checks
Description
docs: fix formatting and capitalization in README.md

docs: fix formatting and capitalization in README.md

---

CHANGELOG.md
laktory/_version.py

version-bump-0.8.1

---

CHANGELOG.md
laktory/_version.py

version-bump-0.8.5

---

CHANGELOG.md
laktory/_version.py

version-bump-0.8.6

---

CHANGELOG.md
laktory/_version.py

version-bump-0.8.7

---

CHANGELOG.md
laktory/_version.py

version-bump-0.8.8

---

CHANGELOG.md
laktory/_version.py

version-bump-0.8.10
